version: "3.9"
services:
  api:     
    build: .
    image: uricbonatti/dna-analysis
    container_name: dna-analysis-api
    ports: 
      - "3333:8000"
    networks:
      - challenge
    environment:
      DB_URL: "mongodb://mongodb:27017"
      MAX_REQUESTS:
      MINUTES_RESEND_REQUEST:
    volumes:
      - dna-analysis-logs:/usr/project/logs/
    depends_on:
      - "mongodb"
  
  mongodb:
    image: mongo
    container_name: dna-analysis-db
    volumes:
      - dna-analysis_data:/data/db/  
    networks: 
      - challenge

networks:
  challenge:
    driver: bridge

volumes:
  dna-analysis-logs:
  dna-analysis_data:
